### ISSUE TITLE
Typeshare panics when encountering slice of user type.

### ISSUE THREAD

**Issue by LouisGariepy** [1Password/typeshare#126]
For example, a struct like so:
```rust
#[typeshare]
#[derive(Serialize)]
pub struct Video<'a> {
    pub tags: &'a [Tag],
}
```
Running typeshare gives an error like so:
```
thread 'main' panicked at 'failed to parse a rust type: Unexpected token when parsing type: `[Tag]`. This is an internal error, please ping a typeshare developer to resolve this problem.', /home/louisgariepy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typeshare-cli-1.6.0/src/main.rs:267:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`Tag` is a simple enum which is also annotated with  `#[typeshare]`.

According to the error message, the error happens because of the slice type `[Tag]`.

Note that changing `&'a [Tag]` for `&'a Vec<Tag>` makes things work.

**Comment by czocher** [comment]
@InquisitivePenguin @CerulanLumina I can try to tackle this issue if you find it worthwhile to support slices.

**Comment by InquisitivePenguin** [comment]
@czocher We should be supporting slices, yes (at least for types that are `Serialize`-only). Feel free to tackle this issue, though we can also look into this.

**Comment by czocher** [comment]
@InquisitivePenguin I'll try to work on it after #120
