### ISSUE TITLE
Is it possible for typeshare to be a dev dependency?

### ISSUE THREAD

**Issue by prestontw** [1Password/typeshare#13]
Hello! I’m very excited for this tool, but I’m a little confused why typeshare isn’t a dev dependency. It seems mostly to deal with code generation, so it shouldn’t really need any functionality while running.

The main thing that I think might be required as a dependency is serde. But serialization/deserialization during runtime seems like a separate concern than code and type generation. (I’m away from my computer, for several weeks, so it’s hard for me to test if this works.)

Thank you for this tool, and thank you for your answers!

**Comment by InquisitivePenguin** [comment]
Are you talking about `typeshare` under the `lib` folder? That's actually a crate for common shared types, like U53 or DateTime. The actual code generation is done by `typeshare-cli`, which can be installed separately and is not required as a dependency for your project.

**Comment by prestontw** [comment]
Ahh, great, thank you for the clarification! That answers my question. I didn't understand which pieces were responsible for which functionality.
