### ISSUE TITLE
`Cow` is not handled correctly

### ISSUE THREAD

**Issue by j-tai** [1Password/typeshare#133]
With the following code:
```rust
use std::borrow::Cow;

use typeshare::typeshare;

#[typeshare]
pub struct Foo<'a> {
    value: Cow<'a, str>,
}
```
Since serde (de)serializes `Cow<str>` as a string, I expected Typeshare to output:
```ts
export interface Foo {
	value: string;
}
```
Instead, it outputs:
```ts
export interface Foo {
	value: Cow<string>;
}
```

## Steps to reproduce

```console
$ git clone https://git.jtai.ca/repro/typeshare-1.git
$ cd typeshare-1
$ typeshare . --lang=typescript --output-file=out.ts
```

**Comment by czocher** [comment]
`typeshare` does a 1:1 conversion of every type that doesn't have a corresponding one in the result language. To compensate for this, you can specify the result type manually:

```Rust
use std::borrow::Cow;

use typeshare::typeshare;

#[typeshare]
pub struct Foo<'a> {
    #[typeshare(serialized_as = "string")]
    value: Cow<'a, str>,
}

```

**Comment by j-tai** [comment]
That works, thanks! I think it would be nice if Typeshare could do this out of the box.

**Comment by CerulanLumina** [comment]
Hey! I'll look into creating a mapping of smart pointers that serde can deserialize from that automatically get typeshared as their inner type!

**Comment by CerulanLumina** [comment]
I've created PR #134 to add this improvement!
