### ISSUE TITLE
`HashMap<_, u32>` is Record not Map

### ISSUE THREAD

**Issue by HHogg** [1Password/typeshare#200]
Hi, I have something similar to the rust code below. What I'm seeing at runtime compared to the typeshare generated types don't match up. Is this supported? is there an annotation that needs to be used for this? or a bug? 

```rust
#[derive(Hash, Serialize)]
#[typeshare]
#[serde(tag = "type", content = "index")]
pub enum Foo {
  Bar,
  Bing,
  Bang(u32),
}


#[derive(Serialize)]
#[typeshare]
pub struct FooParent {
  foos: HashMap<Foo, u32>;
}
```

wasm-bindgen returns 

```ts
export interface FooParent { 
  foos: Map<Foo, number> 
};
```

typeshare returns 

```ts
export interface FooParent { 
  foos: Record<Foo, number>;
}
```

**Comment by HHogg** [comment]
By using `serialized_as = "Map<Foo, u32>")`

```rust
#[derive(Serialize)]
#[typeshare]
pub struct FooParent {
  #[typeshare(serialized_as = "Map<Foo, u32>")]
  foos: HashMap<Foo, u32>;
}
```

The types can be generated like 

```ts
export interface FooParent { 
  foos: Map<Foo, number> 
};
```

**Comment by kjvalencik** [comment]
`serialized_as` is a good solution to the problem if you need `Map`. `typeshare` is primarily written with JSON serialization in mind. A JSON object is defined as `Record<K, V>` in TypeScript. `Map` refers to the [`Map` class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

**Comment by HHogg** [comment]
@kjvalencik Thanks for the reply. I was also looking into the option of serializing as an object, by stringifying the complex key type, but I couldn't get that to work as in the serializer it needed the key to have a  `static &str` life time. Maybe there is a way to do it, but I couldn't work it out... 

However the Map type is just as useful to me in the code so I went back to changing typeshare and got it working like the above. I guess I have 2 questions:

- Should the Typeshare's result match up with the default behaviour of Bindgen? 
- How would I generate a `Record<K, V>` from a HashMap?

**Comment by kjvalencik** [comment]
> Should the Typeshare's result match up with the default behaviour of Bindgen?
The defaults align with `JSON` instead of wasm-bindgen. The default matches what `serde_json` + `JSON.parse` produces.

> How would I generate a Record<K, V> from a HashMap?

[Configure serde_wasm_bindgen](https://docs.rs/serde-wasm-bindgen/latest/serde_wasm_bindgen/#serializer-configuration-options) to use `.serialize_maps_as_objects(true)`.

**Comment by HHogg** [comment]
Thanks @kjvalencik I'll give that a try. Happy to close this down!
