### ISSUE TITLE
Macro params to override generated type

### ISSUE THREAD

**Issue by fluxxu** [1Password/typeshare#22]
Thanks for the tool!
Currently this struct
```rust
#[typeshare]
pub struct OrderItem {
  #[ts(type = "any | null")]
  pub meta: Option<Value>,
}
```
will generate this ts type
```typescript
export interface OrderItem {
	meta?: Value;
}
```
where `Value` is `serde_json::Value`
I wonder if it's a good idea to support something like this
```rust
#[typeshare]
pub struct OrderItem {
  #[typeshare(type = "any | null")]
  pub meta: Option<Value>,
}
```

**Comment by InquisitivePenguin** [comment]
Thanks for opening this issue! I like the idea behind this, but we'd need some way to specify that an override is for a particular language.

**Comment by Alfred-Mountfield** [comment]
Would it be possible to just have something like `#[typeshare(js_type = "...", swift_type = "...", kotlin_type = "...")`?

I think an escape hatch like this is essential, you inevitably run into issues with combinations of `serde` tags, especially when you start dealing with `serde(flatten)`. My experience with these libraries are unfortunately TypeScript focused, but I hope Kotlin and Swift don't complicate it too much, some escape hatches in other libraries includes: 

**[Tsify's attribute macro](https://github.com/madonoharu/tsify)**
```rust
use tsify::Tsify;

#[derive(Tsify)]
pub struct Foo {
    #[tsify(type = "0 | 1 | 2")]
    x: i32,
}
```

**[`ts-rs`'s attribute macro](https://github.com/madonoharu/tsify)**
```rust
use ts_rs::TS;

#[derive(TS)]
#[ts(export)]
pub struct Foo {
    #[ts(type = "0 | 1 | 2")]
    x: i32,
}
```

**Comment by InquisitivePenguin** [comment]
Hi @Alfred-Mountfield, and sorry for the wait! I'm going to be implementing a solution starting on Monday.

**Comment by HHogg** [comment]
It would be really handy to have this, a case that I have is `chrono::NaiveDateTime` being serialized as a `string` but typeshare is still outputting as a `NaiveDateTime`. 

```rust
#[derive(Serialize)]
#[typeshare]
pub struct MyStruct {
  timestamp: NaiveDateTime,
}
```

```typescript
export interface MyStruct {
  timestamp: NaiveDateTime;
}
```

Would be really handy to do something like ...

```rust
pub struct MyStruct {
  #[typeshare(typescript = "string")]
  timestamp: NaiveDateTime,
}

```

**Comment by HHogg** [comment]
Just adding a workaround I'm using. Anything that I need to be output as something else, I stick the same named thing in a separate file and add the Typeshare annotation to that. It wouldn't work for `null` or `any`. But it works well for something like a String. E.g. 

```rs
// Workaround types for typeshare
// -----------------------------

// https://github.com/1Password/typeshare/issues/110
#[typeshare]
pub type Transform = String;

// https://github.com/1Password/typeshare/issues/110
#[typeshare]
pub type NodeId = String;

// https://github.com/1Password/typeshare/issues/34
#[typeshare]
pub type NaiveDateTime = String;

// -----------------------------

```
