### ISSUE TITLE
Unexpected token when parsing type: `[u16 ; 9]`

### ISSUE THREAD

**Issue by takkuumi** [1Password/typeshare#32]
thread '<unnamed>' panicked at 'failed to parse a rust type: Unexpected token when parsing type: `[u16 ; 9]`. This is an internal error, please ping a typeshare developer to resolve this problem.', /Users/takumi/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/typeshare-cli-1.0.1/src/main.rs:234:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by CerulanLumina** [comment]
Hello! Typeshare currently does not support fixed size arrays. For now, use `Vec<u16>` instead. The returned panic message is misleading though - I'll create a new issue to improve this.

**Comment by NateLing** [comment]
@CerulanLumina could it map this to `number[]`

**Comment by InquisitivePenguin** [comment]
Closed by #89
