### ISSUE TITLE
Inconsistant CLI binary name usage

### ISSUE THREAD

**Issue by NuroDev** [1Password/typeshare#4]
## What

Currently the majority of the documentation references installing the `typeshare-cli` but then running `typeshare` to invoke it why currently does not work out-the-box unless you alias `typeshare` to `typeshare-cli`.

## Possible fix

Either update the documentation to use `typeshare-cli` everywhere, rename the CLI binary from `typeshare-cli` to just `typeshare` or offer some kind of shortcut / alias for the binary out-the-box (Not looked into Cargo binary distribution in a while so can't remember / don't know if this is possible)

**Comment by InquisitivePenguin** [comment]
Thanks for opening this, looking into it.
