### ISSUE TITLE
Represent the supported languages as an enum

### ISSUE THREAD

**Issue by Czocher** [1Password/typeshare#68]
Currently some parts of the code, like [here](https://github.com/1Password/typeshare/blob/main/core/src/rust_types.rs#L41), represent the supported languages as a `String`. In reality this string will always be one of the supported language names - `typescript`, `swift`, `go`, `kotlin`.
We should represent the supported languages as an `enum` instead.

**Comment by InquisitivePenguin** [comment]
Fixed in #72
