### ISSUE TITLE
Error when running cargo install

### ISSUE THREAD

**Issue by martinmr** [1Password/typeshare#80]
I am running cargo install on a binary indirectly dependent on typeshare and I get this error:

```
error: expected serde try_from attribute to be a string: `try_from = "..."`
   --> /home/martinmr/.cargo/registry/src/github.com-1ecc6299db9ec823/typeshare-1.0.1/src/integer.rs:34:28
    |
34  |           #[serde(try_from = $untruncated_str)]
    |                              ^^^^^^^^^^^^^^^^
...
114 | / truncated_type!(
115 | |     U53,
116 | |     u64,
117 | |     "u64",
...   |
120 | |     "The 53-bit unsigned integer type. Purpose of this type is to mimic JavaScript's integer type."
121 | | );
    | |_- in this macro invocation
    |
    = note: this error originates in the macro `truncated_type` (in Nightly builds, run with -Z macro-backtrace for more info)

error: expected serde try_from attribute to be a string: `try_from = "..."`
   --> /home/martinmr/.cargo/registry/src/github.com-1ecc6299db9ec823/typeshare-1.0.1/src/integer.rs:34:28
    |
34  |           #[serde(try_from = $untruncated_str)]
    |                              ^^^^^^^^^^^^^^^^
...
126 | / truncated_type!(
127 | |     I54,
128 | |     i64,
129 | |     "i64",
...   |
132 | |     "The 54-bit signed integer type. Purpose of this type is to mimic JavaScript's integer type."
133 | | );
    | |_- in this macro invocation
    |
    = note: this error originates in the macro `truncated_type` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `typeshare` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
^C  Building [======================>  ] 278/294: tantivy, cargo-lock, libgit2-sys(build)
```

I didn't get it the first time I ran the command, but I get it every time after. Running `cargo clean` doesn't help.

**Comment by martinmr** [comment]
It's this commit if that's helpful: https://github.com/trane-project/trane-cli/commit/97bb86986304fdeb26928f08ba14ac71064267f3

**Comment by martinmr** [comment]
Building the project that actually uses typeshare works fine though

**Comment by martinmr** [comment]
Same issue when trying to run cargo build on this commit https://github.com/trane-project/trane/commit/f514d797d9068d2b231d56f6b1149ea64dad92cc in the CI pipeline but not on my machine.

For the other project, it fails on my machine.

**Comment by martinmr** [comment]
With the verbose options, this is the command that fails (when running cargo install):
```
 Running `rustc --crate-name typeshare --edition=2021 /home/martinmr/.cargo/registry/src/github.com-1ecc6299db9ec823/typeshare-1.0.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=c4b0fdffe14b4c70 -C extra-filename=-c4b0fdffe14b4c70 --out-dir /home/martinmr/workspace/trane-cli/target/release/deps -L dependency=/home/martinmr/workspace/trane-cli/target/release/deps --extern chrono=/home/martinmr/workspace/trane-cli/target/release/deps/libchrono-0e2048e71587b9a1.rmeta --extern serde=/home/martinmr/workspace/trane-cli/target/release/deps/libserde-87bdc9edf8e487c8.rmeta --extern serde_json=/home/martinmr/workspace/trane-cli/target/release/deps/libserde_json-47ebd281091542fa.rmeta --extern typeshare_annotation=/home/martinmr/workspace/trane-cli/target/release/deps/libtypeshare_annotation-21829e58750ce549.so --cap-lints allow`
 ```

And this command succeeds (when running `cargo build --release`):
```
 Running `rustc --crate-name typeshare --edition=2021 /home/martinmr/.cargo/registry/src/github.com-1ecc6299db9ec823/typeshare-1.0.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=e5ce113263e3518a -C extra-filename=-e5ce113263e3518a --out-dir /home/martinmr/workspace/trane-cli/target/release/deps -L dependency=/home/martinmr/workspace/trane-cli/target/release/deps --extern chrono=/home/martinmr/workspace/trane-cli/target/release/deps/libchrono-3c55daee8812e281.rmeta --extern serde=/home/martinmr/workspace/trane-cli/target/release/deps/libserde-822396222001a2f4.rmeta --extern serde_json=/home/martinmr/workspace/trane-cli/target/release/deps/libserde_json-7cb68a3d609e826c.rmeta --extern typeshare_annotation=/home/martinmr/workspace/trane-cli/target/release/deps/libtypeshare_annotation-0710c1877a4ad673.so --cap-lints allow`
 ```
 
 The paths to serde, etc are different, but I am not sure if that's expected.

**Comment by martinmr** [comment]
I've reverted the addition of typeshare for now to unblock my project, but the commits linked above are still available for helping you debug the issue. I also saw docs.rs fail to build the previous release (the first one to introduce typeshare), so I don't think the issue is specific to my machine.

**Comment by takkuumi** [comment]
same

**Comment by peter-kehl** [comment]
Hi @martinmr. I've tried to reproduce your with first commit (https://github.com/trane-project/trane-cli/commit/97bb86986304fdeb26928f08ba14ac71064267f3), on current Arch/Manjaro Linux x64 kernel `6.2.7-2` (standard target `x86_64-unknown-linux-gnu`), with either
- yesterday's `nightly: rustc 1.70.0-nightly (1db9c061d 2023-03-21)` and
- recent `stable: rustc `1.68.0 (2c8cc3432 2023-03-06)`,
but both build (`cargo build`) and install (`cargo install --path .`) well:
```bash
# with stable:
trane-cli (97bb869) is 📦 v0.13.2 via 🦀 v1.68.0 took 6m3s 
❯ trane --version
...
Trane Version: 0.13.2
CLI Version: 0.13.2
Commit Hash: 97bb86986304fdeb26928f08ba14ac71064267f3

trane >>
```
Please, share about your `rustup`, toolchains, architecture... anything.

**Comment by peter-kehl** [comment]
I've tried to reproduce the second commit ()
❯ # stable

trane (f514d79) is 📦 v0.13.3 via 🦀 v1.68.1 
❯ cargo clippy
    Checking cfg-if v1.0.0

**Comment by peter-kehl** [comment]
@martinmr Please provide steps (ideally with a new local user) to get to the point when you could run the above `rustc --crate-name typeshare --edition=2021 /home/martinmr/.cargo/registry/src/github.com-1ecc6299db9ec823/typeshare-1.0.1 ...`.

Why? After I run `cargo build` (with `stable`) under the same `trane-cli` commit as your local (`97bb869`), I do not have any `~.cargo/registry/src/github-com*`, only `/home/pkehl/.cargo/registry/cache/index.crates.io-6f17d22bba15001f` (after my previous cleanup). Any chance you have global dependency overrides (instead of `crates.io` to GIT) or anything else?
```bash
trane-cli (97bb869) is 📦 v0.13.2 via 🦀 v1.68.1 
❯ find ~/.cargo/registry/* -name "typeshare*"
/home/pkehl/.cargo/registry/cache/index.crates.io-6f17d22bba15001f/typeshare-1.0.1.crate
/home/pkehl/.cargo/registry/cache/index.crates.io-6f17d22bba15001f/typeshare-annotation-1.0.2.crate
/home/pkehl/.cargo/registry/index/index.crates.io-6f17d22bba15001f/.cache/ty/pe/typeshare
/home/pkehl/.cargo/registry/index/index.crates.io-6f17d22bba15001f/.cache/ty/pe/typeshare-annotation
/home/pkehl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typeshare-annotation-1.0.2
/home/pkehl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typeshare-1.0.1
```

**Comment by martinmr** [comment]
I am no longer able to reproduce it either after I upgraded from rust 1.68.0 to 1.68.1. I'll try to readd my typeshare changes to master and see if I can perform the commands I could not before.

**Comment by martinmr** [comment]
Readded the typeshare changes to my project and I was able to make it work after upgrading to 1.68.1
